const Database = require('better-sqlite3');
const db = new Database('foodchain.db');
const total = db.prepare('SELECT COUNT(1) as c FROM dish_catalog').get().c;
console.log('Total:', total);
const sample = db.prepare('SELECT name, cuisine, category FROM dish_catalog LIMIT 10').all();
for (const s of sample) console.log(s.name + ' | ' + s.cuisine + ' | ' + s.category);
const byCat = db.prepare('SELECT category, COUNT(1) as c FROM dish_catalog GROUP BY category ORDER BY c DESC').all();
console.log('\nBy category:');
for (const c of byCat) console.log(c.category + ': ' + c.c);
const byCuis = db.prepare('SELECT cuisine, COUNT(1) as c FROM dish_catalog GROUP BY cuisine ORDER BY c DESC').all();
console.log('\nBy cuisine:');
for (const c of byCuis) console.log(c.cuisine + ': ' + c.c);
const noCuis = db.prepare("SELECT COUNT(1) as c FROM dish_catalog WHERE cuisine = ''").get().c;
console.log('\nNo cuisine:', noCuis);
db.close();
